set(LIB3DS_INCLUDE_DIR ${LIB3DS_ROOT_DIR}/include)
set(LIB3DS_BIN_DIR ${LIB3DS_ROOT_DIR}/bin)
SET(LIB3DS_LIB_DIR ${LIB3DS_ROOT_DIR}/lib/debug)
file(GLOB lib_files ${LIB3DS_LIB_DIR}/*.lib)
foreach(lib_file ${lib_files})
  set(LIB3DS_LIBRARIES ${LIB3DS_LIBRARIES} debug ${lib_file})
endforeach()
SET(LIB3DS_LIB_DIR ${LIB3DS_ROOT_DIR}/lib/release)
file(GLOB lib_files ${LIB3DS_LIB_DIR}/*.lib)
foreach(lib_file ${lib_files})
  set(LIB3DS_LIBRARIES ${LIB3DS_LIBRARIES} optimized ${lib_file})
endforeach()